title: Stanislao Zompì
url: "https://stanislao92.github.io"
theme: jekyll-theme-minimal

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "CV"
   link: "cvzompi.pdf"
 - name: "Research"
   link: "research"
